spring:
  datasource:
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book-storedb?allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8000
  servlet:
      context-path: /bookstore
